before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update

  # Now we can install the newer docker-engine which is required for the newer
  # docker-composer we will install next. The messy options are to force it to
  # be non-interactive (normally it asks you a bunch of config questions).
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce

  # Print out the current docker-compose version. Once this reports 1.6+ then we
  # do not need the following steps.
  - docker-compose --version

  # Check that docker-compose is now running the latest version (or at least the
  # one we specified). This is not to be confused with the version we printed
  # before doing the update.
  - docker-compose --version

  - cp .env.docker .env
  - docker-compose up -d
  - docker-compose exec php bash -c "cd /var/www/api && composer install"
  - docker-compose exec php bash -c "cd /var/www/api && php artisan migrate && php artisan passport:install --force"

script:
  - docker-compose exec php bash -c "cd /var/www/api && vendor/bin/phpunit"