before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update

  # Now we can install the newer docker-engine which is required for the newer
  # docker-composer we will install next. The messy options are to force it to
  # be non-interactive (normally it asks you a bunch of config questions).
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce

  # Print out the current docker-compose version. Once this reports 1.6+ then we
  # do not need the following steps.
  - docker-compose --version

  # Check that docker-compose is now running the latest version (or at least the
  # one we specified). This is not to be confused with the version we printed
  # before doing the update.
  - docker-compose --version

  - cp .env.docker .env
  - docker-compose up -d
script:
  - docker-compose exec php bash -c "composer install && php artisan migrate:refresh --seed && php artisan passport:install --force"
  - docker-compose exec php bash -c "php artisan db:seed --class=AlterPasswordClientSecret"
  - docker-compose exec php bash -c "chmod 777 storage -R"
  - docker-compose run --rm newman newman run  https://www.getpostman.com/collections/3fa92bb5e0eec30072a9 -e postman_environment.json
  - docker-compose exec php bash -c "cd /var/www/api && vendor/bin/phpunit"
  - docker-compose exec php bash -c "cat storage/logs/laravel.log"