version: '2'
services:
  nginx:
    build: ./build/nginx
    ports:
     - ${DOCKER_NGINX_PORT}
    volumes:
     - ./:/var/www/api
    networks:
     - appnet
  php:
    build: ./build/php
    volumes:
     - ./:/var/www/api
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
