version: '2'
services:
  nginx:
    image: shippingdocker/nginx:latest
    ports:
     - "8082:80"
    volumes:
     - ./:/var/www/html
    networks:
     - appnet
  php:
    image: shippingdocker/php:latest
    volumes:
     - ./:/var/www/html
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    volumes:
     - data:/var/lib/elasticsearch
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
